language: node.js
node_js: 7
install: "npm install && npm run build"
script:

before_install:
- openssl aes-256-cbc -K $encrypted_512b2015aa14_key -iv $encrypted_512b2015aa14_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 47.106.127.210

after_success:
  - scp dist/* root@47.106.127.210:/var/www/html
